---
title: "about"
---

This page is under construction (all of these pages are under construction -- some of it is more
obvious than others, except when i'm explicitly sign-posting!)

I study social cognitive development and am passionate about how people learn and reason about
coordinating with each other. Most of this website + the body of work I've produced is about that.
(Of endless confusion to people: I publish under Hok but my real last name is Kim.)

In addition to developmental psychology, I'm excited about metascience and digital scholarship. I
am a big believer in university libraries and their role in the ecosystem of scholarship +
knowledge production. CREOS is doing incredible and important work. I had a brief moment between
grad school and my postdoc working with Harvard Libraries on their digital scholarship initiative
(view their 3D scans of objects here). In particular, I assisted on this Cluny exhibit at the
Graduate School of Design by annotating this scan of the Bernward Column.

In graduate school, I organized with GSU and served as the division representative of the Social
Sciences on the steering committee. I served as a student board member of the Cognitive Development
Society. I've had some brief stints in industry. I worked at Disney on a movie app for collectors,
and at Amtrak on their innovation team. I studied philosophy in undergrad (I am very passionate
about Kierkegaard) and got my start doing qualitative work in a narrative analysis lab.

I love to read, I play the bass, I like live jazz and electronic music, I am drawn to images of
speed and the firmament. I have an overly-indulgent goodreads. I may or may not be a south park
fan.
